// llms.txt generator. Produces a structured, machine-readable map of the store
// per the llms.txt convention (https://llmstxt.org) so AI assistants can
// understand the brand and its products. Platform-agnostic: reads the catalog
// through the PlatformPort, so it works for Shopify and WordPress alike.
import type { Tenant } from "@geo/db";
import { prisma } from "@geo/db";
import type { CatalogItem, PlatformPort } from "../ports";

/** Strip HTML tags + collapse whitespace, then clamp to `max` chars. */
function clean(text: string | null, max = 180): string {
  if (!text) return "";
  const t = text.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  return t.length > max ? `${t.slice(0, max - 1).trimEnd()}…` : t;
}

export interface LlmsTxtResult {
  content: string;
  productCount: number;
}

export async function generateLlmsTxt(
  platform: PlatformPort,
  tenant: Tenant,
): Promise<LlmsTxtResult> {
  const [profile, products] = await Promise.all([
    platform.getStoreProfile(tenant),
    platform.listProducts(tenant),
  ]);
  const base = profile.primaryUrl.replace(/\/$/, "");
  const name = profile.name || tenant.externalId;

  const lines: string[] = [];
  lines.push(`# ${name}`);
  lines.push("");
  if (profile.description) lines.push(`> ${clean(profile.description, 240)}`);
  else lines.push(`> Online store. AI-readable product map generated by GEO Monitor.`);
  lines.push("");
  lines.push(
    `This file helps AI assistants accurately describe and recommend ${name} and its products.`,
  );
  lines.push("");

  // Group by product type for a navigable structure.
  const byType = new Map<string, CatalogItem[]>();
  for (const p of products) {
    const key = p.productType?.trim() || "Products";
    if (!byType.has(key)) byType.set(key, []);
    byType.get(key)!.push(p);
  }

  for (const [type, items] of byType) {
    lines.push(`## ${type}`);
    lines.push("");
    for (const p of items) {
      const url = p.url || `${base}/products/${p.handle ?? ""}`;
      const desc = clean(p.description);
      lines.push(desc ? `- [${p.title}](${url}): ${desc}` : `- [${p.title}](${url})`);
    }
    lines.push("");
  }

  return { content: lines.join("\n").trimEnd() + "\n", productCount: products.length };
}

export async function saveLlmsTxt(tenantId: string, content: string) {
  await prisma.tenant.update({
    where: { id: tenantId },
    data: { llmsTxt: content, llmsTxtGeneratedAt: new Date() },
  });
}
